// <auto-generated />
namespace FUp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Table_Fichiers_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Table_Fichiers_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201801122040242_User_Table_Fichiers_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
